spring.application.name=gym-tracker

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-tcwh2grqlnid2plt.us.auth0.com/
auth0.audience=https://gym-tracker-api

spring.datasource.url=${JDBC_DATABASE_URL}
spring.datasource.username=${JDBC_DATABASE_USERNAME}
spring.datasource.password=${JDBC_DATABASE_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update

spring.jpa.open-in-view= false

api.ninjas.key=${API_NINJAS_KEY:EDs9X2dLBoMSI99xqJO0TWnmYUj05vPdrxzZ4nK2}

